////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./regdefs.h
//
// Project:	ArrowZip, a demonstration of the Arrow MAX1000 FPGA board
//
// DO NOT EDIT THIS FILE!
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	../../../autofpga/trunk/sw/autofpga ../../../autofpga/trunk/sw/autofpga -o . global.txt bkram.txt buserr.txt clock.txt dlyarbiter.txt rtclight.txt sdram.txt flexpress.txt pic.txt pwrcount.txt memsdev.txt spio.txt version.txt hbconsole.txt zipbones.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2018, Gisselquist Technology, LLC
//
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of  the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
//
// License:	GPL, v3, as defined and found on www.gnu.org,
//		http://www.gnu.org/licenses/gpl.html
//
//
////////////////////////////////////////////////////////////////////////////////
//
//
#ifndef	REGDEFS_H
#define	REGDEFS_H


//
// The @REGDEFS.H.INCLUDE tag
//
// @REGDEFS.H.INCLUDE for masters
// @REGDEFS.H.INCLUDE for peripherals
// And finally any master REGDEFS.H.INCLUDE tags
// End of definitions from REGDEFS.H.INCLUDE


//
// Register address definitions, from @REGS.#d
//
// CONSOLE registers
#define	R_CONSOLE_FIFO  	0x00200004	// 00200000, wbregs names: UFIFO
#define	R_CONSOLE_UARTRX	0x00200008	// 00200000, wbregs names: RX
#define	R_CONSOLE_UARTTX	0x0020000c	// 00200000, wbregs names: TX
#define	R_BUSERR        	0x00400000	// 00400000, wbregs names: BUSERR
#define	R_BUSERR        	0x00400000	// 00400000, wbregs names: BUSERR
#define	R_PIC           	0x00400004	// 00400004, wbregs names: PIC
#define	R_PIC           	0x00400004	// 00400004, wbregs names: PIC
#define	R_PWRCOUNT      	0x00400008	// 00400008, wbregs names: PWRCOUNT
#define	R_PWRCOUNT      	0x00400008	// 00400008, wbregs names: PWRCOUNT
#define	R_SPIO          	0x0040000c	// 0040000c, wbregs names: SPIO
#define	R_SPIO          	0x0040000c	// 0040000c, wbregs names: SPIO
#define	R_VERSION       	0x00400010	// 00400010, wbregs names: VERSION
#define	R_VERSION       	0x00400010	// 00400010, wbregs names: VERSION
// The bus timer
#define	R_TIMER         	0x00600000	// 00600000, wbregs names: TIMER
// The bus timer
#define	R_TIMER         	0x00600000	// 00600000, wbregs names: TIMER
// The watchdog timer
#define	R_WATCHDOG      	0x00600200	// 00600200, wbregs names: WATCHDOG
// The watchdog timer
#define	R_WATCHDOG      	0x00600200	// 00600200, wbregs names: WATCHDOG
// RTC clock registers
#define	R_CLOCK         	0x00600400	// 00600400, wbregs names: CLOCK, TIMER
#define	R_TIMER         	0x00600404	// 00600400, wbregs names: TIMER
#define	R_STOPWATCH     	0x00600408	// 00600400, wbregs names: STOPWATCH
#define	R_CKALARM       	0x0060040c	// 00600400, wbregs names: ALARM, CKALARM
// RTC clock registers
#define	R_CLOCK         	0x00600400	// 00600400, wbregs names: CLOCK, TIMER
#define	R_TIMER         	0x00600404	// 00600400, wbregs names: TIMER
#define	R_STOPWATCH     	0x00600408	// 00600400, wbregs names: STOPWATCH
#define	R_CKALARM       	0x0060040c	// 00600400, wbregs names: ALARM, CKALARM
// MEMS register(s)
#define	R_MEMS          	0x00600600	// 00600600, wbregs names: $(DEVID)
// MEMS register(s)
#define	R_MEMS          	0x00600600	// 00600600, wbregs names: $(DEVID)
#define	R_BKRAM         	0x00800000	// 00800000, wbregs names: RAM
#define	R_FLASH         	0x01000000	// 01000000, wbregs names: FLASH
#define	R_SDRAM         	0x01800000	// 01800000, wbregs names: SDRAM


//
// The @REGDEFS.H.DEFNS tag
//
// @REGDEFS.H.DEFNS for masters
#define	CLKFREQHZ	80000000
#define	R_ZIPCTRL	0x02000000
#define	R_ZIPDATA	0x02000004
#define	RESET_ADDRESS	0x00800000
// @REGDEFS.H.DEFNS for peripherals
// No defines yet
#define	BKRAMBASE	0x00800000
#define	BKRAMLEN	0x00008000
#define	SDRAMBASE	0x01800000
#define	SDRAMLEN	0x00800000
#define	SDRAMLGLEN	23
#define	FLASHBASE	0x01000000
#define	FLASHLEN	0x00800000
#define	FLASHLGLEN	23
// @REGDEFS.H.DEFNS at the top level
// End of definitions from REGDEFS.H.DEFNS
//
// The @REGDEFS.H.INSERT tag
//
// @REGDEFS.H.INSERT for masters

#define	CPU_GO		0x0000
#define	CPU_RESET	0x0040
#define	CPU_INT		0x0080
#define	CPU_STEP	0x0100
#define	CPU_STALL	0x0200
#define	CPU_HALT	0x0400
#define	CPU_CLRCACHE	0x0800
#define	CPU_sR0		0x0000
#define	CPU_sSP		0x000d
#define	CPU_sCC		0x000e
#define	CPU_sPC		0x000f
#define	CPU_uR0		0x0010
#define	CPU_uSP		0x001d
#define	CPU_uCC		0x001e
#define	CPU_uPC		0x001f


// @REGDEFS.H.INSERT for peripherals


// @REGDEFS.H.INSERT from the top level
typedef	struct {
	unsigned	m_addr;
	const char	*m_name;
} REGNAME;

extern	const	REGNAME	*bregs;
extern	const	int	NREGS;
// #define	NREGS	(sizeof(bregs)/sizeof(bregs[0]))

extern	unsigned	addrdecode(const char *v);
extern	const	char *addrname(const unsigned v);
// End of definitions from REGDEFS.H.INSERT


#endif	// REGDEFS_H
