////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./board.h
//
// Project:	ArrowZip, a demonstration of the Arrow MAX1000 FPGA board
//
// DO NOT EDIT THIS FILE!
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	../../../autofpga/trunk/sw/autofpga ../../../autofpga/trunk/sw/autofpga -o . global.txt bkram.txt buserr.txt clock.txt dlyarbiter.txt rtclight.txt sdram.txt flexpress.txt pic.txt pwrcount.txt memsdev.txt spio.txt version.txt hbconsole.txt zipbones.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2018, Gisselquist Technology, LLC
//
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of  the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
//
// License:	GPL, v3, as defined and found on www.gnu.org,
//		http://www.gnu.org/licenses/gpl.html
//
//
////////////////////////////////////////////////////////////////////////////////
//
//
#ifndef	BOARD_H
#define	BOARD_H

// And, so that we can know what is and isn't defined
// from within our main.v file, let's include:
#include <design.h>

#include <design.h>
#include <cpudefs.h>

#define	_HAVE_ZIPBONES



typedef struct  CONSOLE_S {
	unsigned	u_setup;
	unsigned	u_fifo;
	unsigned	u_rx, u_tx;
} CONSOLE;



#define	SPIO_BTN_LEFT	0x00100
#define	SPIO_BTN_RIGHT	0x00100


typedef	struct	RTCLIGHT_S	{
	unsigned	r_clock, r_stopwatch, r_timer, r_alarm;
} RTCLIGHT;


#define	CLKFREQHZ	80000000


#ifdef	BUSCONSOLE_ACCESS
#define	_BOARD_HAS_BUSCONSOLE
static volatile CONSOLE *const _uart = ((CONSOLE *)0x00200000);
#endif	// BUSCONSOLE_ACCESS
#define	_BOARD_HAS_VERSION
#ifdef	SPIO_ACCESS
#define	_BOARD_HAS_SPIO
static volatile unsigned *const _spio = ((unsigned *)4194316);
#endif	// SPIO_ACCESS
#ifdef	BUSPIC_ACCESS
#define	_BOARD_HAS_BUSPIC
static volatile unsigned *const _buspic = ((unsigned *)0x00400004);
#endif	// BUSPIC_ACCESS
#ifdef	MEMS_ACCESS
#define	_BOARD_HAS_MEMS_SENSOR
extern char _mems[@$NBYTES];
#endif	// MEMS_ACCESS
#ifdef	RTC_ACCESS
#define	_BOARD_HAS_RTCLIGHT
static volatile RTCLIGHT *const _rtc = ((RTCLIGHT *)0x00600400);
#endif	// RTC_ACCESS
#ifdef	BKRAM_ACCESS
#define	_BOARD_HAS_BKRAM
extern char	_bkram[0x00008000];
#endif	// BKRAM_ACCESS
#define	_BOARD_HAS_BUSERR
static volatile unsigned *const _buserr = ((unsigned *)4194304);
#ifdef	SDRAM_ACCESS
#define	_BOARD_HAS_SDRAM
extern char _sdram[0x00800000];
#endif	// SDRAM_ACCESS
#ifdef	FLASH_ACCESS
#define	_BOARD_HAS_FLASH
extern char _flash[0x00800000];
#endif	// FLASH_ACCESS
//
// Interrupt assignments (1 PICs)
//
// PIC: buspic
#define	BUSPIC_TMC	BUSPIC(0)
#define	BUSPIC_UARTTXF	BUSPIC(1)
#define	BUSPIC_UARTRXF	BUSPIC(2)
#define	BUSPIC_UARTTX	BUSPIC(3)
#define	BUSPIC_UARTRX	BUSPIC(4)
#define	BUSPIC_SPIO	BUSPIC(5)
#define	BUSPIC_MEMSDONE	BUSPIC(6)
#define	BUSPIC_MEMSB	BUSPIC(7)
#define	BUSPIC_MEMSA	BUSPIC(8)
#define	BUSPIC_RTC	BUSPIC(9)
#endif	// BOARD_H
