////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./main_tb.cpp
//
// Project:	ArrowZip, a demonstration of the Arrow MAX1000 FPGA board
//
// DO NOT EDIT THIS FILE!
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	../../../autofpga/trunk/sw/autofpga ../../../autofpga/trunk/sw/autofpga -o . global.txt bkram.txt buserr.txt clock.txt dlyarbiter.txt rtclight.txt sdram.txt flexpress.txt pic.txt pwrcount.txt memsdev.txt spio.txt version.txt hbconsole.txt zipbones.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2018, Gisselquist Technology, LLC
//
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of  the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
//
// License:	GPL, v3, as defined and found on www.gnu.org,
//		http://www.gnu.org/licenses/gpl.html
//
//
////////////////////////////////////////////////////////////////////////////////
//
//
//
// SIM.INCLUDE
//
// Looking for string: SIM.INCLUDE
#include "verilated.h"
#include "Vmain.h"
#define	BASECLASS	Vmain

#include "design.h"
#include "regdefs.h"
#include "testb.h"
#include "byteswap.h"
#include "zipelf.h"

#include "sdramsim.h"
#include "dbluartsim.h"
#include "dspiflashsim.h"
//
// SIM.DEFINES
//
// Looking for string: SIM.DEFINES
#ifndef VVAR
#ifdef  NEW_VERILATOR
#define VVAR(A) main__DOT_ ## A
#else
#define VVAR(A) v__DOT_ ## A
#endif
#endif

#define	block_ram	VVAR(_bkrami__DOT__mem)
#ifndef	VVAR
#ifdef	NEW_VERILATOR
#define	VVAR(A)	main__DOT_ ## A
#else
#define	VVAR(A)	v__DOT_ ## A
#endif
#endif

#define	cpu_break 	VVAR(_swic__DOT__cpu_break)
#define	cpu_cmd_halt	VVAR(_swic__DOT__cmd_halt)
#define	cpu_ipc		VVAR(_swic__DOT__thecpu__DOT__ipc)
#define	cpu_upc		VVAR(_swic__DOT__thecpu__DOT__r_upc)
#define	cpu_gie		VVAR(_swic__DOT__thecpu__DOT__r_gie)
#define	cpu_iflags	VVAR(_swic__DOT__thecpu__DOT__w_iflags)
#define	cpu_uflags	VVAR(_swic__DOT__thecpu__DOT__w_uflags)
#define	cpu_regs	VVAR(_swic__DOT__thecpu__DOT__regset)
#define	cpu_cmd_addr	VVAR(_swic__DOT__cmd_addr)
#define	cpu_bus_err	VVAR(_swic__DOT__thecpu__DOT__bus_err)
#define	cpu_ibus_err	VVAR(_swic__DOT__thecpu__DOT__ibus_err_flag)
#define	cpu_ubus_err	VVAR(_swic__DOT__thecpu__DOT__r_ubus_err_flag)
#define	cpu_mem_rdaddr	VVAR(_swic__DOT__thecpu__DOT__domem__DOT__rdaddr)
#define	cpu_mem_wraddr	VVAR(_swic__DOT__thecpu__DOT__domem__DOT__wraddr)
#define	cpu_op_sim	VVAR(_swic__DOT__thecpu__DOT__op_sim)
#define	cpu_op_valid	VVAR(_swic__DOT__thecpu__DOT__op_valid)
#define	cpu_alu_ce	VVAR(_swic__DOT__thecpu__DOT__alu_ce)
#define	cpu_new_pc	VVAR(_swic__DOT__thecpu__DOT__new_pc)
#define	cpu_sim_immv	VVAR(_swic__DOT__thecpu__DOT__op_sim_immv)

class	MAINTB : public TESTB<Vmain> {
public:
		// SIM.DEFNS
// Looking for string: SIM.DEFNS
	int	m_cpu_bombed;
#ifdef	SDRAM_ACCESS
	SDRAMSIM	*m_sdram;
#endif
	DBLUARTSIM	*m_hb;
#ifdef	FLASH_ACCESS
	QSPIFLASHSIM	*m_flash;
#endif
	MAINTB(void) {
		// From zip
		m_cpu_bombed = 0;
		// From sdram
#ifdef	SDRAM_ACCESS
	m_sdram = new SDRAMSIM();
#endif
		// From hb
		m_hb = new DBLUARTSIM();
		m_hb->setup(80);
		// From flash
#ifdef	FLASH_ACCESS
	m_flash = new QSPIFLASHSIM(FLASHLGLEN);
	m_last_qspi_dat = 15;
#endif
	}

	void	reset(void) {
// Looking for string: SIM.SETRESET
		m_core->cpu_reset = 1;
		m_core->i_clk = 1;
		m_core->eval();
// Looking for string: SIM.CLRRESET
	}

	void	trace(const char *vcd_trace_file_name) {
		fprintf(stderr, "Opening TRACE(%s)\n",
				vcd_trace_file_name);
		opentrace(vcd_trace_file_name);
		m_time_ps = 0;
	}

	void	close(void) {
		m_done = true;
	}

	void	tick(void) {
		if (done())
			return;
		// KYSIM.TICK tags
// Looking for string: SIM.TICK
#ifdef	INCLUDE_ZIPCPU
		// ZipCPU Sim instruction support
		if ((m_core->cpu_op_sim)
			&&(m_core->cpu_op_valid)
			&&(m_core->cpu_alu_ce)
			&&(!m_core->cpu_new_pc)) {
			//
			execsim(m_core->cpu_sim_immv);
		}

		if (m_core->cpu_break) {
			printf("\n\nBOMB : CPU BREAK RECEIVED\n");
			m_cpu_bombed++;
			dump(m_core->cpu_regs);
		} else if (m_cpu_bombed) {
			if (m_cpu_bombed++ > 12)
				m_done = true;
		}
#endif	// INCLUDE_ZIPCPU

#ifdef	SDRAM_ACCESS
		m_core->i_ram_data = (*m_sdram)(1,
			m_core->o_ram_cke, m_core->o_ram_cs_n,
				m_core->o_ram_ras_n, m_core->o_ram_cas_n,
				m_core->o_ram_we_n, m_core->o_ram_bs,
				m_core->o_ram_addr, m_core->o_ram_drive_data,
				m_core->o_ram_data, m_core->o_ram_dqm);

#endif
		m_core->i_hb_uart_rx = (*m_hb)(m_core->o_hb_uart_tx);
#ifdef	FLASH_ACCESS

		int	idspi;
		// The toplevel logic creates a one cycle/clock delay.  Emulate
		// it here.
		m_core->i_dspi_dat = m_last_dspi_dat;
		if ((m_core->o_dspi_sck == 3)||(m_core->o_dspi_sck == 0)) {
			idspi = m_flash(m_core->o_dspi_cs_n,
						m_core->o_dspi_sck&1,
						m_core->o_dspi_dat);
		} else {
			idspi = m_flash(m_core->o_dspi_cs_n,
						(m_core->o_dspi_sck&2)?1:0,
						m_core->o_dspi_dat);
			idspi = m_flash(m_core->o_dspi_cs_n,
						(m_core->o_dspi_sck&1)?1:0,
						m_core->o_dspi_dat);
		}
		if (m_core->o_dspi_mod&2) {
			// If we are driving the lines, drive the inputs
			// as well.
			if (m_core->o_dspi_mod&1)
				; // 2'b11	// Not driving any lines
			else	// 2'b10
				idspi = m_core->o_dspi_dat;
		} else {
			// 2'b0x
			//
			// Turn on top two bits (unused in SPI mode)
			idspi |= 0xc;
			// Replace bottom bit with o_dspi_dat[0]
			idspi &= 0xe; // Turn off bottom bit
			idspi |= m_core->o_dspi_dat&1;
		}
		m_last_dspi_dat = idspi;

		m_core->i_dspi_dat = (*m_flash)(m_core->o_dspi_cs_n,
			m_core->o_dspi_sck, m_core->o_dspi_dat);
#endif
		TESTB<Vmain>::tick();

		bool	writeout = false;

			// KYSIM.DBGCONDITION tags
// Looking for string: SIM.DBGCONDITION

			if (writeout) {
					// KYSIM.DEBUG tags
// Looking for string: SIM.DEBUG
		}
	}

	bool	load(uint32_t addr, const char *buf, uint32_t len) {
		uint32_t	start, offset, wlen, base, naddr;

		base  = 0x00800000;
		naddr = 0x00002000;

		if ((addr >= base)&&(addr < base + naddr)) {
			// If the start access is in bkram
			start = (addr > base) ? (addr-base) : 0;
			offset = (start + base) - addr;
			wlen = (len-offset > naddr - start)
				? (naddr - start) : len - offset;
#ifdef	BKRAM_ACCESS
			// FROM bkram.SIM.LOAD
			start = start & (-4);
			wlen = (wlen+3)&(-4);

			// Need to byte swap data to get it into the memory
			char	*bswapd = new char[len+8];
			memcpy(bswapd, &buf[offset], wlen);
			byteswapbuf(len>>2, (uint32_t *)bswapd);
			memcpy(&m_core->block_ram[start], bswapd, wlen);
			delete	bswapd;
			// AUTOFPGA::Now clean up anything else
			// Was there more to write than we wrote?
			if (addr + len > base + naddr)
				return load(base + naddr, &buf[offset+wlen], len-wlen);
			return true;
#else	// BKRAM_ACCESS
			return false;
#endif	// BKRAM_ACCESS
		}

		base  = 0x01800000;
		naddr = 0x00200000;

		if ((addr >= base)&&(addr < base + naddr)) {
			// If the start access is in sdram
			start = (addr > base) ? (addr-base) : 0;
			offset = (start + base) - addr;
			wlen = (len-offset > naddr - start)
				? (naddr - start) : len - offset;
#ifdef	SDRAM_ACCESS
			// FROM sdram.SIM.LOAD
			m_sdram->load(start, &buf[offset], wlen);
			// AUTOFPGA::Now clean up anything else
			// Was there more to write than we wrote?
			if (addr + len > base + naddr)
				return load(base + naddr, &buf[offset+wlen], len-wlen);
			return true;
#else	// SDRAM_ACCESS
			return false;
#endif	// SDRAM_ACCESS
		}

		base  = 0x01000000;
		naddr = 0x00200000;

		if ((addr >= base)&&(addr < base + naddr)) {
			// If the start access is in flash
			start = (addr > base) ? (addr-base) : 0;
			offset = (start + base) - addr;
			wlen = (len-offset > naddr - start)
				? (naddr - start) : len - offset;
#ifdef	FLASH_ACCESS
			// FROM flash.SIM.LOAD
			m_flash->load(start, &buf[offset], wlen);
			// AUTOFPGA::Now clean up anything else
			// Was there more to write than we wrote?
			if (addr + len > base + naddr)
				return load(base + naddr, &buf[offset+wlen], len-wlen);
			return true;
#else	// FLASH_ACCESS
			return false;
#endif	// FLASH_ACCESS
		}

		return false;
	}

	//
	// KYSIM.METHODS
	//
// Looking for string: SIM.METHODS

	void	loadelf(const char *elfname) {
		ELFSECTION	**secpp, *secp;
		uint32_t	entry;

		elfread(elfname, entry, secpp);

		for(int s=0; secpp[s]->m_len; s++) {
			secp = secpp[s];

			load(secp->m_start, secp->m_data, secp->m_len);
		} free(secpp);
	}


	bool	gie(void) {
		return (m_core->cpu_gie);
	}

	void dump(const uint32_t *regp) {
		uint32_t	uccv, iccv;
		fflush(stderr);
		fflush(stdout);
		printf("ZIPM--DUMP: ");
		if (gie())
			printf("Interrupts-enabled\n");
		else
			printf("Supervisor mode\n");
		printf("\n");

		iccv = m_core->cpu_iflags;
		uccv = m_core->cpu_uflags;

		printf("sR0 : %08x ", regp[0]);
		printf("sR1 : %08x ", regp[1]);
		printf("sR2 : %08x ", regp[2]);
		printf("sR3 : %08x\n",regp[3]);
		printf("sR4 : %08x ", regp[4]);
		printf("sR5 : %08x ", regp[5]);
		printf("sR6 : %08x ", regp[6]);
		printf("sR7 : %08x\n",regp[7]);
		printf("sR8 : %08x ", regp[8]);
		printf("sR9 : %08x ", regp[9]);
		printf("sR10: %08x ", regp[10]);
		printf("sR11: %08x\n",regp[11]);
		printf("sR12: %08x ", regp[12]);
		printf("sSP : %08x ", regp[13]);
		printf("sCC : %08x ", iccv);
		printf("sPC : %08x\n",regp[15]);

		printf("\n");

		printf("uR0 : %08x ", regp[16]);
		printf("uR1 : %08x ", regp[17]);
		printf("uR2 : %08x ", regp[18]);
		printf("uR3 : %08x\n",regp[19]);
		printf("uR4 : %08x ", regp[20]);
		printf("uR5 : %08x ", regp[21]);
		printf("uR6 : %08x ", regp[22]);
		printf("uR7 : %08x\n",regp[23]);
		printf("uR8 : %08x ", regp[24]);
		printf("uR9 : %08x ", regp[25]);
		printf("uR10: %08x ", regp[26]);
		printf("uR11: %08x\n",regp[27]);
		printf("uR12: %08x ", regp[28]);
		printf("uSP : %08x ", regp[29]);
		printf("uCC : %08x ", uccv);
		printf("uPC : %08x\n",regp[31]);
		printf("\n");
		fflush(stderr);
		fflush(stdout);
	}


	void	execsim(const uint32_t imm) {
		uint32_t	*regp = m_core->cpu_regs;
		int		rbase;
		rbase = (gie())?16:0;

		fflush(stdout);
		if ((imm & 0x03fffff)==0)
			return;
		// fprintf(stderr, "SIM-INSN(0x%08x)\n", imm);
		if ((imm & 0x0fffff)==0x00100) {
			// SIM Exit(0)
			close();
			exit(0);
		} else if ((imm & 0x0ffff0)==0x00310) {
			// SIM Exit(User-Reg)
			int	rcode;
			rcode = regp[(imm&0x0f)+16] & 0x0ff;
			close();
			exit(rcode);
		} else if ((imm & 0x0ffff0)==0x00300) {
			// SIM Exit(Reg)
			int	rcode;
			rcode = regp[(imm&0x0f)+rbase] & 0x0ff;
			close();
			exit(rcode);
		} else if ((imm & 0x0fff00)==0x00100) {
			// SIM Exit(Imm)
			int	rcode;
			rcode = imm & 0x0ff;
			close();
			exit(rcode);
		} else if ((imm & 0x0fffff)==0x002ff) {
			// Full/unconditional dump
			printf("SIM-DUMP\n");
			dump(regp);
		} else if ((imm & 0x0ffff0)==0x00200) {
			// Dump a register
			int rid = (imm&0x0f)+rbase;
			printf("%8lu @%08x R[%2d] = 0x%08x\n", m_time_ps/1000,
			m_core->cpu_ipc, rid, regp[rid]);
		} else if ((imm & 0x0ffff0)==0x00210) {
			// Dump a user register
			int rid = (imm&0x0f);
			printf("%8lu @%08x uR[%2d] = 0x%08x\n", m_time_ps/1000,
				m_core->cpu_ipc,
				rid, regp[rid+16]);
		} else if ((imm & 0x0ffff0)==0x00230) {
			// SOUT[User Reg]
			int rid = (imm&0x0f)+16;
			printf("%c", regp[rid]&0x0ff);
		} else if ((imm & 0x0fffe0)==0x00220) {
			// SOUT[User Reg]
			int rid = (imm&0x0f)+rbase;
			printf("%c", regp[rid]&0x0ff);
		} else if ((imm & 0x0fff00)==0x00400) {
			// SOUT[Imm]
			printf("%c", imm&0x0ff);
		} else { // if ((insn & 0x0f7c00000)==0x77800000)
			uint32_t	immv = imm & 0x03fffff;
			// Simm instruction that we dont recognize
			// if (imm)
			// printf("SIM 0x%08x\n", immv);
			printf("SIM 0x%08x (ipc = %08x, upc = %08x)\n", immv,
				m_core->cpu_ipc,
				m_core->cpu_upc);
		} fflush(stdout);
	}


};
